### PR TITLE
Support sxl 1.0.15

### PR DESCRIPTION
**Pull request by emiltin**
This PR updates the TLC emulator to pass all tests currently in the rsmp_validator.
It includes some refactorings and fixes as well.

### CODE REVIEW

**Review by GunnarRolander — COMMENTED** [review]
Looks good! I don't feel qualified enough to spot any errors in the logic of it, so I'll leave approval to David 👍

**Comment by emiltin** [comment]
updated. we need to check if this has introduced any issues when testing with equipment

**Comment by emiltin** [comment]
With timers set to 0.1s and timeouts to 0.2s I can run all tests against the Ruby TLC comsistently in around 4.5s,

**Comment by emiltin** [comment]
Merging.

**Pull request merged**
